# Generated by Django 4.1.3 on 2023-01-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="identifier",
            field=models.IntegerField(default=0),
        ),
    ]
