# Generated by Django 4.1.3 on 2023-01-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_animal_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="initial_weight",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.weight"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="purchase_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="sector",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.sector"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="total_days",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="area",
            field=models.FloatField(null=True),
        ),
    ]
