# Generated by Django 4.1.3 on 2023-01-07 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_group_initial_weight_alter_group_purchase_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietSupplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="animal",
            old_name="identifier",
            new_name="badge_number",
        ),
        migrations.RemoveField(
            model_name="diet",
            name="supplements",
        ),
        migrations.RemoveField(
            model_name="supplement",
            name="units",
        ),
        migrations.DeleteModel(
            name="SupplementSet",
        ),
        migrations.AddField(
            model_name="dietsupplement",
            name="diet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.diet"
            ),
        ),
        migrations.AddField(
            model_name="dietsupplement",
            name="supplement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.supplement"
            ),
        ),
    ]
