# Generated by Django 4.1.3 on 2023-01-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_dietsupplement_rename_identifier_animal_badge_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="initial_weight",
        ),
        migrations.RemoveField(
            model_name="group",
            name="phases",
        ),
        migrations.RemoveField(
            model_name="group",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="group",
            name="total_days",
        ),
        migrations.RemoveField(
            model_name="phase",
            name="weights",
        ),
        migrations.RemoveField(
            model_name="weight",
            name="current_days",
        ),
        migrations.AddField(
            model_name="animal",
            name="purchase_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="animals",
            field=models.ManyToManyField(to="api.animal"),
        ),
    ]
