# Generated by Django 4.2 on 2023-04-20 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('supplement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.supplement')),
            ],
        ),
    ]
